### ISSUE TITLE
Could not find package

### ISSUE THREAD

**Issue by rottenoats** [iulyanp/elixir-mix-bundle#2]
> [InvalidArgumentException]                                                   
>   Could not find package iulyanp/elixir-mix-bundle at any version matching yo  
>   ur PHP version 5.5.9.0

When running `composer require iulyanp/elixir-mix-bundle` at the root of my `symfony3` project. 

Any ideas? Not available for PHP 5.5 or for Symfony3? Thanks

**Comment by iulyanp** [comment]
Hello, 

The bundle doesn't support PHP v5.5.9 only 5.6 or 7.*.
Sorry for my late response.
